/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
package mx.maleficarum.calixta;

import com.auronix.calixta.sms.SMSGateway;
import org.mule.tools.cloudconnect.annotations.Connector;
import org.mule.tools.cloudconnect.annotations.Operation;

/**
 * Sends SMS using Calixta (calixta.com.mx) service
 *
 * @author maleficarum (http://maleficarum.mx)
 */
@Connector(namespacePrefix="calixta")
public class CalixtaCloudConnector {

	private SMSGateway gateway;

	public CalixtaCloudConnector() {
		gateway = new SMSGateway();
	}

    @Operation
    public Object send(String destination, String text) {
		Object payload = null;
		try {
			payload = Integer.valueOf(gateway.sendMessage(destination,text));
		} catch(Exception e) {
			payload = e.getLocalizedMessage();
			e.printStackTrace();
		}
		return payload;
    }
}
