/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
package mx.maleficarum.calixta;

import org.junit.Test;

import mx.maleficarum.calixta.CalixtaCloudConnector;

public class CalixtaTestCase
{
    @Test
    public void invokeSomeMethodOnTheCloudConnector()
    {
    /*
        Add code that tests the cloud connector at the API level. This means that you'll
        instantiate your cloud connector directly, invoke one of its methods and assert
        you get the correct result.

        Example:

        CalixtaCloudConnector connector = new CalixtaCloudConnector();
        Object result = connector.someMethod("sample input");
        assertEquals("expected output", result);
     */
    }
}
